version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5000"
    environment:
      - POSTGRES_DB=demodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=polpot
  backend:
    container_name: backend
    build:
    ports:
      - "8080:5001"
    depends_on:
      - postgres
  nginx:
    container_name: nginx
    image: proxy
    build: ./.nginx
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
